version: "3"

services:
  customer-console:
    build:
      context: .
    container_name: customer-console
    image: customer-console
    restart: always
    environment:
      REACT_APP_LOGO: img/appicon.png
      REACT_APP_COMPANYNM: Holding (Thailand) Co., Ltd.
      PORT: 3000
    ports:
      - 8004:3000
    # volumes:
    #   - /home/deploy/customer-console/.env:/usr/src/app/.env
