export const tabOptions = [
  "Profile",
  "Contact",
  "Identity",
  "Consent",
  "Workplace",
  "Residence",
  "Education",
  "Peculiar",
  "Cash Account",
  "Product",
  "Engagement",
];

export const fieldNames = [
  [
    "User Id",
    "Customer Id",
    "Name (Thai)",
    "Name (English)",
    "Risk Factor",
    "Risk reason",
    "Device Id",
    "Updated at",
    "Created at",
  ],
  ["Phone number", "Email", "Registered Address"],
  [
    "Nationality",
    "DOB",
    "National id",
    "Passport",
    "Issue date",
    "Expire date",
  ],
  [],
  ["Company name", "Work Address"],
  ["Registered Address"],
  [],
  [],
  [],
  [],
  [],
];

export const customerData = [
  [
    "user_id",
    "customer_id",
    "fullname_th",
    "fullname_en",
    "risk_factor",
    "risk_reason",
    "device_id",
    "updated_at",
    "created_at",
  ],
  [{0:"phone"},{0:"email"}, {1:"address_line1"}],
  [
    "nationality",
    "dob",
    "national_id",
    "passport",
    "issue_date",
    "expire_date",
  ],
  [],
  [{2:"company_name"},{1:"address_line1"}],
  [{1:"address_line1"}],
  [],
  [],
  [],
  [],
  [],
];
